// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShopPIN.Server.Data;

#nullable disable

namespace WebShopPIN.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230222193615_Users")]
    partial class Users
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebShopPIN.Shared.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rolex",
                            Url = "rolex"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Audemars Piguet",
                            Url = "audemars"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Patek Philippe",
                            Url = "patek"
                        });
                });

            modelBuilder.Entity("WebShopPIN.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Description = "The Rolex Oyster Perpetual Date GMT Master is part of the Rolex Professional Watch Collection. Designed in collaboration with the now defunct Pan American Airways of the United States for use by their pilots and navigators, it was launched in 1954.",
                            ImageUrl = "https://sep.yimg.com/ay/movadobaby/rolex-oyster-perpetual-gmt-master-ii-116710-120.jpg",
                            Title = "Rolex GMT Master II"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Description = "Rolex introduced the “Cosmograph Daytona” in 1963, ten years after introducing their first Oyster-case chronograph model. The watch featured the Cosmograph name on the dial, and Rolex chose to connect it with auto racing due to the tachymeter printed on the bezel. This was a distinct departure from previous Rolex chronographs, which located any such markings under the crystal, and became the signature feature of the Cosmograph model.",
                            ImageUrl = "https://www.uhren-wiki.com/images/Rolex_Oyster_Perpetual_Cosmograph_Daytona.jpg",
                            Title = "Rolex Daytona Cosmograph"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Description = "The Rolex Oyster Perpetual Submariner is a line of sports watches designed for diving and manufactured by Rolex, resistant to water and corrosion. The first Submariner was introduced to the public in 1954 at the Basel Watch Fair. It was the first watch to be waterproof up to 100m. The Rolex Submariner is considered 'a classic among wristwatches' manufactured by one of the most widely recognized luxury brands in the world. Due to its huge popularity, there are many homage watches by well-established watchmakers, as well as illegal counterfeits. The Rolex Submariner is part of Rolex's Oyster Perpetual line.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/c/cd/Rolex-Submariner.jpg",
                            Title = "Rolex Submariner"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            Description = "The \"Royal Oak\" (named after a famous sailing ship of the British fleet) contributed significantly to the success and awareness of the Audemars Piguet brand and, like the Oyster models from Rolex, can now be counted among the product icons of modern times.",
                            ImageUrl = "https://www.uhren-wiki.com/images/Audemars_Piguet_Royal_Oak_Chronograph_Tourbillon.jpg",
                            Title = "Audemars Piguet Royal Oak"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            Description = "Launched in 2019, Code 11.59 by Audemars Piguet writes a new page in the Manufacture’s history. The contemporary evolution of a classic round watch, it presents a multifaceted and curved architecture with more details than meet the eyes.",
                            ImageUrl = "https://cdn2.chrono24.com/images/uhren/23580782-szpxfk8cnofx7bgmkoa13808-ExtraLarge.jpg",
                            Title = "Audemars Piguet Code 11.59"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Description = "Named after one of its founders, the Jules Audemars collection takes cues from more traditional Audemars Piguet designs. In 1875, Jules Audemars created about 20 very complex movements, which he later used as collateral when he and Edward Piguet founded Audemars Piguet & Cie in 1881. These movements marked the beginning of Audemars Piguet. All watches in this collection have a circular shape, some of which also feature complications such as tourbillon, minute repeater, and perpetual calendar.",
                            ImageUrl = "https://www.luxuriousmagazine.com/wp-content/uploads/2011/09/audemars-onlywatch2011-1.jpg",
                            Title = "Audemars Piguet Jules Audemars"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 3,
                            Description = "The Patek Philippe Nautilus is an iconic luxury sports watch that has become a symbol of style and status among watch enthusiasts. Designed by the legendary watch designer Gérald Genta in the 1970s, the Nautilus has a distinctive shape that resembles a porthole on a ship, with a rounded octagonal bezel and integrated bracelet.",
                            ImageUrl = "https://static.patek.com/images/articles/face_white/350/5740_1G_001_1.jpg",
                            Title = "Patek Philippe Nautilus"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 3,
                            Description = "The Calatrava is the quintessential dress watch, with a timeless, classic design that has remained largely unchanged since its introduction in 1932. The watch features a round case, simple but elegant dial with a small seconds sub-dial, and thin, tapered hour markers. The Calatrava is available in a range of materials, from stainless steel to precious metals such as gold and platinum, and with a variety of dial colors and textures. The watch is hand-wound and has a relatively slim profile, making it an ideal choice for dressier occasions.",
                            ImageUrl = "https://www.swissluxury.com/product_images/5196G_001.jpg",
                            Title = "Patek Philippe Calatrava"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            Description = "The Aquanaut is a sportier and more contemporary alternative to the Nautilus, featuring a distinctive rounded octagonal case and an integrated rubber strap. The watch has a bold and modern design, with a range of dial colors, including black, blue, and brown, and luminescent hands and hour markers for enhanced legibility in low-light conditions. The Aquanaut is water-resistant to 120 meters and is equipped with a self-winding movement with a power reserve of up to 45 hours.",
                            ImageUrl = "https://www.jewelsintime.com/wp-content/uploads/2022/12/jit_221222-071407_1853228860.jpg",
                            Title = "Patek Philippe Aquanaut"
                        });
                });

            modelBuilder.Entity("WebShopPIN.Shared.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Batman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Root Beer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pepsi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Stainless steel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "White dial"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Black ceramic"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Blue dial"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Black dial"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Smoked grey dial"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Silver dial"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Brown leather"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Green dial"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Rose gold"
                        });
                });

            modelBuilder.Entity("WebShopPIN.Shared.ProductVariant", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 1,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 2,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 1,
                            ProductTypeId = 3,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 4,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 5,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 2,
                            ProductTypeId = 6,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductTypeId = 12,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductTypeId = 7,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 3,
                            ProductTypeId = 4,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductTypeId = 13,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductTypeId = 7,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 4,
                            ProductTypeId = 8,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductTypeId = 7,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductTypeId = 8,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 5,
                            ProductTypeId = 9,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductTypeId = 5,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductTypeId = 7,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 6,
                            ProductTypeId = 10,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 7,
                            ProductTypeId = 13,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 7,
                            ProductTypeId = 10,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 7,
                            ProductTypeId = 7,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductTypeId = 5,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductTypeId = 11,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 8,
                            ProductTypeId = 7,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductTypeId = 10,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductTypeId = 8,
                            OriginalPrice = 1999m,
                            Price = 999m
                        },
                        new
                        {
                            ProductId = 9,
                            ProductTypeId = 7,
                            OriginalPrice = 1099m,
                            Price = 999m
                        });
                });

            modelBuilder.Entity("WebShopPIN.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebShopPIN.Shared.Product", b =>
                {
                    b.HasOne("WebShopPIN.Shared.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("WebShopPIN.Shared.ProductVariant", b =>
                {
                    b.HasOne("WebShopPIN.Shared.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShopPIN.Shared.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("WebShopPIN.Shared.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
